data:extend({
  { type = "item-group", name = "cartmen-1",
	order = "a-a",
	inventory_order = "a-a",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/cartmen-1.png",
  },
  {type = "item-subgroup", name = "cartmen-plates", group = "cartmen-1", order = "a"},
  {type = "item-subgroup", name = "cartmen-parts", group = "cartmen-1", order = "b-a"},
  {type = "item-subgroup", name = "cartmen-parts-2", group = "cartmen-1", order = "b-b"},
  {type = "item-subgroup", name = "cartmen-parts-3", group = "cartmen-1", order = "b-c"},
  {type = "item-subgroup", name = "cartmen-parts-4", group = "cartmen-1", order = "b-d"},
  {type = "item-subgroup", name = "cartmen-packs", group = "cartmen-1", order = "z"},
  {type = "item-subgroup", name = "cartmen-alloy", group = "cartmen-1", order = "d"},
  {type = "item-subgroup", name = "cartmen-silicon", group = "cartmen-1", order = "e"},
  
  { type = "item-group", name = "cartmen-2",
	order = "a-b",
	inventory_order = "a-b",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/cartmen-2.png",
  },
  {type = "item-subgroup", name = "cartmen-electronics-1", group = "cartmen-2", order = "a-a"},
  {type = "item-subgroup", name = "cartmen-electronics-2", group = "cartmen-2", order = "a-b"},
  {type = "item-subgroup", name = "cartmen-electronics-3", group = "cartmen-2", order = "a-c"},
  {type = "item-subgroup", name = "cartmen-cable", group = "cartmen-2", order = "b"},
  {type = "item-subgroup", name = "cartmen-circuits", group = "cartmen-2", order = "c"},
  {type = "item-subgroup", name = "cartmen-energy", group = "cartmen-2", order = "f"},
  {type = "item-subgroup", name = "cartmen-packs-2", group = "cartmen-2", order = "z"},
  
  { type = "item-group", name = "cartmen-3",
	order = "a-c",
	inventory_order = "b-b",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/cartmen-3.png",
  },
  {type = "item-subgroup", name = "cartmen-basic-chemicals", group = "cartmen-3", order = "a-a"},
  {type = "item-subgroup", name = "cartmen-gas", group = "cartmen-3", order = "b"},
  {type = "item-subgroup", name = "cartmen-epoxy", group = "cartmen-3", order = "c"},
  {type = "item-subgroup", name = "cartmen-petrolchemics", group = "cartmen-3", order = "d"},
  {type = "item-subgroup", name = "cartmen-intermediates", group = "cartmen-3", order = "f"},
  {type = "item-subgroup", name = "cartmen-packs-3", group = "cartmen-3", order = "z"},
  
  { type = "item-group", name = "cartmen-4",
	order = "a-d",
	inventory_order = "b-c",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/cartmen-4.png",
  },
  {type = "item-subgroup", name = "cartmen-belt-1", group = "cartmen-4", order = "b-a"},
  {type = "item-subgroup", name = "cartmen-belt-2", group = "cartmen-4", order = "b-b"},
  {type = "item-subgroup", name = "cartmen-belt-3", group = "cartmen-4", order = "b-c"},
  {type = "item-subgroup", name = "cartmen-belt-4", group = "cartmen-4", order = "b-d"},
  {type = "item-subgroup", name = "cartmen-inserter-1", group = "cartmen-4", order = "c-a"},
  {type = "item-subgroup", name = "cartmen-inserter-2", group = "cartmen-4", order = "c-b"},
  
  { type = "item-group", name = "cartmen-5",
	order = "a-e",
	inventory_order = "c-c",
	icon = "__base__/graphics/technology/automation.png",
  },
  {type = "item-subgroup", name = "cartmen-miners", group = "cartmen-5", order = "b"},
  {type = "item-subgroup", name = "cartmen-assemblers", group = "cartmen-5", order = "c"},
  {type = "item-subgroup", name = "cartmen-science-pack-1", group = "cartmen-5", order = "d-a"},
  {type = "item-subgroup", name = "cartmen-science-pack-2", group = "cartmen-5", order = "d-b"},
  {type = "item-subgroup", name = "cartmen-lab", group = "cartmen-5", order = "d-z"},
})