data:extend({
  { type = "recipe", name = "copper-plate",
	icon = "__base__/graphics/icons/copper-plate.png",
	category = "smelting",
	energy_required = 3.5,
	ingredients = {{"copper-ore",1}},
	results = {{type="item",name="copper-plate",amount=1}},
	subgroup = "cartmen-copper",
	order = "a-a-a",
  },
  { type = "recipe", name = "copper-processing-1",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/crushed-copper-ore.png",
	category = "crush",
	--enabled = false,
	energy_required = 10,
	ingredients = {{"copper-ore",2}},
	results = {{type="item",name="crushed-copper",amount=5}},
	subgroup = "cartmen-copper",
	order = "a-b",
  },
  { type = "recipe", name = "copper-casting",
	icon = "__base__/graphics/icons/copper-plate.png",
	category = "blast-furnace",
	--enabled = false,
	energy_required = 3.5,
	ingredients = {{"crushed-copper",3}},
	results = {{type="item",name="copper-plate",amount=1}},
	subgroup = "cartmen-copper",
	order = "a-c",
  },
  { type = "recipe", name = "copper-flotation",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/copper-concentrate.png",
	category = "flotation",
	enabled = false,
	energy_required = 10,
	ingredients = {{"crushed-copper",10}},
	results = {{type="item",name="copper-concentrate",amount=10}--[[,{type="item",name="gold-ore",probability=0.1,amount=1},{type="item",name="silver-ore",probability=0.1,amount=1}]]},
	subgroup = "cartmen-copper",
	order = "b-a",
  },
  { type = "recipe", name = "copper-smelting-2",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/fluid/copper-matte.png",
	category = "blast-furnace",
	enabled = false,
	energy_required = 10,
	ingredients = {{"copper-concentrate",10},{"silicon-plate",2}},
	results = {{type="fluid",name="copper-matte",amount=10},{type="fluid",name="sulfur-dioxide",amount=2.5}},
	subgroup = "cartmen-copper",
	order = "b-b",
  },
  { type = "recipe", name = "copper-smelting-3",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/fluid/copper-blister.png",
	category = "blast-furnace",
	enabled = false,
	energy_required = 10,
	ingredients = {{type="fluid",name="copper-matte",amount=10},{"silicon-plate",2}},
	results = {{type="fluid",name="copper-blister",amount=10},{type="fluid",name="sulfur-dioxide",amount=1.5}},
	subgroup = "cartmen-copper",
	order = "b-c",
  },
  { type = "recipe", name = "copper-casting-2",
	icon = "__base__/graphics/icons/copper-plate.png",
	category = "casting",
	enabled = false,
	energy_required = 2.0,
	ingredients = {{type="fluid",name="copper-blister",amount=10},{"limestone",1}},
	results = {{type="item",name="copper-plate",amount=10}},
	subgroup = "cartmen-copper",
	order = "b-d",
  },
  { type = "recipe", name = "copper-refining",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/plate/copper-anode.png",
	category = "casting",
	enabled = false,
	energy_required = 10,
	ingredients = {{type="fluid",name="copper-blister",amount=5}},
	results = {{type="item",name="copper-anode",amount=8}},
	subgroup = "cartmen-copper",
	order = "c-a",
  },
  { type = "recipe", name = "copper-electro-refining",
	icon = "__base__/graphics/icons/copper-plate.png",
	category = "chemistry",
	enabled = false,
	energy_required = 10,
	ingredients = {{type="item",name="copper-anode",amount=16},{type="fluid",name="sulfuric-acid",amount=4}},
	results = {{type="item",name="copper-plate",amount=16},--[[{type="item",name="gold-ore",probability=0.1,amount=1},{type="item",name="silver-ore",probability=0.1,amount=1}]]},
	subgroup = "cartmen-copper",
	order = "c-b",
  },
  
  { type = "item", name = "crushed-copper",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/crushed-copper-ore.png",
    flags = {"goes-to-main-inventory"},
    stack_size = 200
  },
  { type = "item", name = "copper-concentrate",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/copper-concentrate.png",
    flags = {"goes-to-main-inventory"},
    stack_size = 200
  },
  { type = "item", name = "copper-anode",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/plate/copper-anode.png",
    flags = {"goes-to-main-inventory"},
    stack_size = 200
  },
})