data:extend({
  { type = "recipe", name = "iron-plate",
    icon = "__base__/graphics/icons/iron-plate.png",
	category = "smelting",
	energy_required = 3.5,
	ingredients = {{"iron-ore", 1}},
	results = {{"iron-plate", 1}},
	subgroup = "cartmen-iron",
	order = "a-a",
  },
  { type = "recipe", name = "iron-processing-1",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/crushed-iron-ore.png",
	category = "crush",
	energy_required = 10,
	ingredients = {{"iron-ore", 2}},
	results = {{"crushed-iron", 5}},
	subgroup = "cartmen-iron",
	order = "a-b",
  },
  { type = "recipe", name = "iron-processing-2",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/fluid/liquid-iron.png",
	category = "blast-furnace",
	energy_required = 2.0,
	ingredients = {{"crushed-iron",25},{"coal-coke",1},{"limestone",1}},
	results = {{type="fluid",name="liquid-iron",amount=25},{"iron-slag",2}},
	subgroup = "cartmen-iron",
	order = "a-c",
  },
  { type = "recipe", name = "iron-processing-3",
    icon = "__base__/graphics/icons/iron-plate.png",
	category = "casting",
	energy_required = 2.0,
	ingredients = {{type="fluid",name="liquid-iron",amount=5}},
	results = {{"iron-plate",2}},
	subgroup = "cartmen-iron",
	order = "a-d",
  },
  { type = "recipe", name = "steel-plate",
    icon = "__base__/graphics/icons/steel-plate.png",
	enabled = false,
	category = "smelting",
	energy_required = 17.5,
	ingredients = {{"iron-plate", 3}},
	results = {{"steel-plate", 1}},
	subgroup = "cartmen-iron",
	order = "b-a",
  },
  { type = "recipe", name = "steel-processing-1",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/fluid/liquid-steel.png",
	category = "blast-furnace",
	energy_required = 5.0,
	ingredients = {{type="fluid",name="liquid-iron",amount=10},{"quartz-ore",1},{"nickel-powder",1}},
	results = {{type="fluid",name="liquid-steel",amount=10}},
	subgroup = "cartmen-iron",
	order = "b-b",
  },
  { type = "recipe", name = "steel-processing-2",
    icon = "__base__/graphics/icons/steel-plate.png",
	category = "casting",
	energy_required = 20,
	ingredients = {{type="fluid",name="liquid-steel",amount=5}},
	results = {{"steel-plate", 1}},
	subgroup = "cartmen-iron",
	order = "b-c",
  },
  
  { type = "item", name = "crushed-iron",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/crushed-iron-ore.png",
    flags = {"goes-to-main-inventory"},
    stack_size = 200
  },
  { type = "item", name = "iron-slag",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/iron-slag.png",
    flags = {"goes-to-main-inventory"},
    stack_size = 200
  },
})