data:extend({
  { type = "item", name = "tin-ore",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/tin-ore.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "lead-ore",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/lead-ore.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "quartz-ore",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/quartz.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "titanium-ore",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/titanium-ore.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "zinc-ore",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/zinc-ore.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "nickel-ore",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/nickel-ore.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "limestone",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/limestone.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "tungsten-ore",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/tungsten-ore.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "bauxite-ore",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/bauxite-ore.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
})
