data:extend({
  { type = "recipe", name = "titanium-processing-1",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/crushed-titanium.png",
	category = "crush",
	enabled = false,
	energy_required = 30,
	ingredients = {{"titanium-ore",2}},
	results = {{type="item",name="crushed-titanium",amount=5}},
	subgroup = "cartmen-titanium",
	order = "a",
  },
  { type = "recipe", name = "titanium-extracting",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/fluid/titanium-tetrachloride.png",
	category = "chemistry",
	enabled = false,
	energy_required = 3,
	ingredients = {{type="item",name="crushed-titanium",amount=10},{type="fluid",name="chlorine",amount=5}},
	results = {{type="fluid",name="titanium-tetrachloride",amount=10}},
	subgroup = "cartmen-titanium",
	order = "b",
  },
  { type = "recipe", name = "titanium-purification",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/fluid/titanium-tetrachloride-2.png",
	category = "chemistry",
	enabled = false,
	energy_required = 3,
	ingredients = {{type="fluid",name="titanium-tetrachloride",amount=10}},
	results = {{type="fluid",name="purified-titanium-tetrachloride",amount=6},
			   {type="item",name="magnesium-chloride",amount=2}--,
				--{type="item",name="zirconium-chloride",amount=2}
				},
	subgroup = "cartmen-titanium",
	order = "c",
  },
  { type = "recipe", name = "titanium-sponging",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/titanium-sponge.png",
	category = "chemistry",
	enabled = false,
	energy_required = 3,
	ingredients = {{type="fluid",name="purified-titanium-tetrachloride",amount=10},{type="fluid",name="hydrochloric-acid",amount=2},{type="item",name="magnesium",amount=5}},
	results = {{type="item",name="titanium-sponge",amount=4},{type="item",name="magnesium-chloride",amount=3}},
	subgroup = "cartmen-titanium",
	order = "e",
  },
  
  { type = "recipe", name = "magnesium-chloride-processing",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/chemical/magnesium-chloride.png",
	category = "chemistry",
	enabled = false,
	energy_required = 3,
	ingredients = {{type="item",name="magnesium-chloride",amount=1}},
	results = {{type="item",name="magnesium",amount=1},{type="fluid",name="chlorine",amount=2}},
	subgroup = "cartmen-titanium",
	order = "d",
  },
  
  {type = "item", name = "magnesium-chloride",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/chemical/magnesium-chloride.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },  
  {type = "item", name = "magnesium",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/chemical/magnesium.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },  
  {type = "item", name = "zirconium-chloride",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/chemical/zirconium-chloride.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },  
  {type = "item", name = "zirconium",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/chemical/zirconium.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  {type = "item", name = "crushed-titanium",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/crushed-titanium.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
})