data:extend({
  { type = "recipe", name = "bronze-alloy",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/bronze-ore.png",
	enabled = false,
	energy_required = 4.0,
	ingredients = {{"copper-ore", 3},{"tin-ore",1}},
	results = {{"bronze-ore", 2}},
	subgroup = "cartmen-plates",
	order = "a[alloy]-c[bronze-ore]-a",
  },
  { type = "recipe", name = "bronze-alloy-2",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/plate/bronze-plate.png",
	category = "smelting",
	enabled = false,
	energy_required = 3.5,
	ingredients = {{"bronze-ore", 1}},
	results = {{"bronze-plate", 1}},
	subgroup = "cartmen-plates",
	order = "a[plate]-c[bronze-plate]-b",
  },
  
  { type = "recipe", name = "titanium-alloy",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/plate/titanium-plate.png",
	category = "chemistry",
	enabled = false,
	energy_required = 2.0,
	ingredients = {{"titanium-sponge", 1},{type="fluid",name="liquid-steel",amount=5}},
	results = {{"titanium-plate", 2}},
	subgroup = "cartmen-titanium",
	order = "f",
  },
})