data:extend({   
  { type = "recipe", name = "tin-plate",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/plate/tin-plate.png",
	category = "smelting",
	energy_required = 3.5,
	ingredients = {{"tin-ore", 1}},
	results = {{"tin-plate", 1}},
	subgroup = "cartmen-plates",
	order = "a[plate]-b[tin]",
  },
  
  { type = "recipe", name = "lead-plate",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/plate/lead-plate.png",
	category = "smelting",
	energy_required = 3.5,
	ingredients = {{"lead-ore", 1}},
	results = {{"lead-plate", 1}},
	subgroup = "cartmen-plates",
	order = "a[plate]-e[lead]",
  },
})