data:extend({
  { type = "recipe", name = "resin",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/resin.png",
	category = "crafting",
	enabled = false,
	energy_required = 5.0,
	ingredients = {{"raw-wood",10}},
	results = {{"resin", 1}},
	subgroup = "cartmen-parts-4",
	order = "a[rubber]-a[resin]",
  },
  { type = "recipe", name = "natural-rubber",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/rubber.png",
	category = "smelting",
	enabled = false,
	energy_required = 3.5,
	ingredients = {{"resin",3}},
	results = {{"rubber", 1}},
	subgroup = "cartmen-parts-4",
	order = "a[rubber]-b[natural-rubber]",
  },
  { type = "recipe", name = "synthetic-rubber",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/rubber.png",
	category = "chemistry",
	enabled = false,
	energy_required = 1.0,
	ingredients = {{type="fluid",name="butadiene",amount=2}},
	results = {{"rubber", 1}},
	subgroup = "cartmen-parts-4",
	order = "a[rubber]-c[synthetic-rubber]",
  },
  { type = "recipe", name = "rubber-seal",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/rubber-seal.png",
	enabled = false,
	energy_required = 1.0,
	ingredients = {{"rubber",1}},
	results = {{"rubber-seal", 4}},
	subgroup = "cartmen-parts-4",
	order = "a[rubber]-d[seal]",
  },
  { type = "recipe", name = "rubber-belt",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/rubber-belt.png",
	enabled = false,
	energy_required = 1.0,
	ingredients = {{"rubber",1}},
	results = {{"rubber-belt", 1}},
	subgroup = "cartmen-parts-4",
	order = "a[rubber]-e[drive-belt]",
  },
})