data:extend({
  { type = "recipe", name = "science-pack-1",
    icon = "__base__/graphics/icons/science-pack-1.png",
	energy_required = 10,
	ingredients = {{type="item",name="copper-parts",amount=5}},
	results = {{type="item",name="science-pack-1",amount=1}},
	subgroup = "cartmen-science-pack-1",
	order = "a-a",
  },
  { type = "recipe", name = "science-pack-1-2",
    icon = "__base__/graphics/icons/science-pack-1.png",
	energy_required = 8,
	ingredients = {{type="item",name="bronze-parts",amount=4}},
	results = {{type="item",name="science-pack-1",amount=1}},
	subgroup = "cartmen-science-pack-1",
	order = "a-b",
  },
  { type = "recipe", name = "science-pack-1-3",
    icon = "__base__/graphics/icons/science-pack-1.png",
	energy_required = 10,
	ingredients = {{type="item",name="iron-parts",amount=3}},
	results = {{type="item",name="science-pack-1",amount=1}},
	subgroup = "cartmen-science-pack-1",
	order = "a-c",
  },
  { type = "recipe", name = "science-pack-1-4",
    icon = "__base__/graphics/icons/science-pack-1.png",
	energy_required = 10,
	ingredients = {{type="item",name="steel-parts",amount=2}},
	results = {{type="item",name="science-pack-1",amount=1}},
	subgroup = "cartmen-science-pack-1",
	order = "a-d",
  },
  { type = "recipe", name = "science-pack-1-5",
    icon = "__base__/graphics/icons/science-pack-1.png",
	energy_required = 10,
	ingredients = {{type="item",name="titanium-parts",amount=1}},
	results = {{type="item",name="science-pack-1",amount=1}},
	subgroup = "cartmen-science-pack-1",
	order = "a-e",
  },
  
  { type = "recipe", name = "science-pack-2",
    icon = "__base__/graphics/icons/science-pack-2.png",
	energy_required = 10,
	ingredients = {{type="item",name="circuit-pack-1",amount=5}},
	results = {{type="item",name="science-pack-2",amount=1}},
	subgroup = "cartmen-science-pack-1",
	order = "b-a",
  },
  { type = "recipe", name = "science-pack-2-2",
    icon = "__base__/graphics/icons/science-pack-2.png",
	energy_required = 8,
	ingredients = {{type="item",name="circuit-pack-2",amount=4}},
	results = {{type="item",name="science-pack-2",amount=1}},
	subgroup = "cartmen-science-pack-1",
	order = "b-b",
  },
  { type = "recipe", name = "science-pack-2-3",
    icon = "__base__/graphics/icons/science-pack-2.png",
	energy_required = 10,
	ingredients = {{type="item",name="circuit-pack-3",amount=3}},
	results = {{type="item",name="science-pack-2",amount=1}},
	subgroup = "cartmen-science-pack-1",
	order = "b-c",
  },
  { type = "recipe", name = "science-pack-2-4",
    icon = "__base__/graphics/icons/science-pack-2.png",
	energy_required = 10,
	ingredients = {{type="item",name="circuit-pack-4",amount=2}},
	results = {{type="item",name="science-pack-2",amount=1}},
	subgroup = "cartmen-science-pack-1",
	order = "b-d",
  },
  { type = "recipe", name = "science-pack-2-5",
    icon = "__base__/graphics/icons/science-pack-2.png",
	energy_required = 10,
	ingredients = {{type="item",name="circuit-pack-5",amount=1}},
	results = {{type="item",name="science-pack-2",amount=1}},
	subgroup = "cartmen-science-pack-1",
	order = "b-e",
  },
  
  { type = "recipe", name = "science-pack-3",
    icon = "__base__/graphics/icons/science-pack-3.png",
	energy_required = 10,
	ingredients = {{type="item",name="chemical-pack-1",amount=5}},
	results = {{type="item",name="science-pack-3",amount=1}},
	subgroup = "cartmen-science-pack-2",
	order = "a-a",
  },
  { type = "recipe", name = "science-pack-3-2",
    icon = "__base__/graphics/icons/science-pack-3.png",
	energy_required = 8,
	ingredients = {{type="item",name="chemical-pack-2",amount=4}},
	results = {{type="item",name="science-pack-3",amount=1}},
	subgroup = "cartmen-science-pack-2",
	order = "a-b",
  },
  { type = "recipe", name = "science-pack-3-3",
    icon = "__base__/graphics/icons/science-pack-3.png",
	energy_required = 10,
	ingredients = {{type="item",name="chemical-pack-3",amount=3}},
	results = {{type="item",name="science-pack-3",amount=1}},
	subgroup = "cartmen-science-pack-2",
	order = "a-c",
  },
  { type = "recipe", name = "science-pack-3-4",
    icon = "__base__/graphics/icons/science-pack-3.png",
	energy_required = 10,
	ingredients = {{type="item",name="chemical-pack-4",amount=2}},
	results = {{type="item",name="science-pack-3",amount=1}},
	subgroup = "cartmen-science-pack-2",
	order = "a-d",
  },
  { type = "recipe", name = "science-pack-3-5",
    icon = "__base__/graphics/icons/science-pack-3.png",
	energy_required = 10,
	ingredients = {{type="item",name="chemical-pack-5",amount=1}},
	results = {{type="item",name="science-pack-3",amount=1}},
	subgroup = "cartmen-science-pack-2",
	order = "a-e",
  },
  
})