data:extend({
  { type = "recipe", name = "wooden-stick",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/wooden-stick.png",
	enabled = true,
	energy_required = 0.5,
	ingredients = {{"wood",1}},
	results = {{"wooden-stick", 2}},
	subgroup = "cartmen-parts-4",
	order = "b[wood]-a[stick]",
  },
  { type = "recipe", name = "copper-cable",
    category = "electronics-hand",
	energy_required = 1,
	icon = "__base__/graphics/icons/copper-cable.png",
	ingredients = {
	{type="item",name="copper-plate",amount=1}
    },
	results = {
	{type="item",name="copper-cable",amount=2}
	},
	subgroup = "cartmen-cable",
	order = "a[copper-cable-1]"
  },
  
  { type = "recipe", name = "copper-gear-wheel",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/copper-gear-wheel.png",
	category = "hand-craft",
	enabled = true,
	energy_required = 2.0,
	ingredients = {{"copper-plate",2}},
	results = {{"copper-gear-wheel", 1}},
	subgroup = "cartmen-parts",
	order = "a[copper]-a[copper-gear-wheel]",
  },
  { type = "recipe", name = "copper-shaft",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/copper-shaft.png",
	category = "hand-craft",
	enabled = true,
	energy_required = 1.5,
	ingredients = {{"copper-plate",1}},
	results = {{"copper-shaft", 1}},
	subgroup = "cartmen-parts",
	order = "a[copper]-b[copper-shaft]",
  },
  { type = "recipe", name = "copper-bolts-screws",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/copper-bolts-screws.png",
	category = "hand-craft",
	enabled = true,
	energy_required = 3.0,
	ingredients = {{"copper-plate",1}},
	results = {{"copper-bolts-screws", 3}},
	subgroup = "cartmen-parts",
	order = "a[copper]-c[copper-bolts-screws]",
  },
  { type = "recipe", name = "copper-parts",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/copper-parts.png",
	category = "part-pack",
	enabled = true,
	energy_required = 10,
	ingredients = {{"copper-gear-wheel", 2},{"copper-shaft", 1},{"copper-bolts-screws", 2}},
	results = {{"copper-parts", 1}},
	subgroup = "cartmen-packs",
	order = "a[part-pack]-a[copper]",
  },
  
  { type = "recipe", name = "bronze-gear-wheel",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/bronze-gear-wheel.png",
	category = "hand-craft",
	enabled = false,
	energy_required = 4.0,
	ingredients = {{"bronze-plate",2}},
	results = {{"bronze-gear-wheel", 1}},
	subgroup = "cartmen-parts",
	order = "b[bronze]-a[bronze-gear-wheel]",
  },
  { type = "recipe", name = "bronze-shaft",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/bronze-shaft.png",
	category = "hand-craft",
	enabled = false,
	energy_required = 3.0,
	ingredients = {{"bronze-plate",1}},
	results = {{"bronze-shaft", 1}},
	subgroup = "cartmen-parts",
	order = "b[bronze]-b[bronze-shaft]",
  },
  { type = "recipe", name = "bronze-bolts-screws",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/bronze-bolts-screws.png",
	category = "hand-craft",
	enabled = false,
	energy_required = 6.0,
	ingredients = {{"bronze-plate",1}},
	results = {{"bronze-bolts-screws", 3}},
	subgroup = "cartmen-parts",
	order = "b[bronze]-c[bronze-bolts-screws]",
  },
  { type = "recipe", name = "bronze-parts",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/bronze-parts.png",
	category = "part-pack",
	enabled = false,
	energy_required = 9,
	ingredients = {{"bronze-gear-wheel", 2},{"bronze-shaft", 1},{"bronze-bolts-screws", 2}},
	results = {{"bronze-parts", 1}},
	subgroup = "cartmen-packs",
	order = "a[part-pack]-b[bronze]",
  },
  
  { type = "recipe", name = "iron-gear-wheel",
    icon = "__base__/graphics/icons/iron-gear-wheel.png",
	category = "hand-craft",
	enabled = false,
	energy_required = 3.0,
	ingredients = {{"iron-plate",2}},
	results = {{"iron-gear-wheel", 1}},
	subgroup = "cartmen-parts",
	order = "c[iron]-a[iron-gear-wheel]",
  },
  { type = "recipe", name = "iron-stick",
    icon = "__base__/graphics/icons/iron-stick.png",
	category = "hand-craft",
	enabled = false,
	energy_required = 2.25,
	ingredients = {{"iron-plate",1}},
	results = {{"iron-stick", 1}},
	subgroup = "cartmen-parts",
	order = "c[iron]-b[iron-shaft]",
  },
  { type = "recipe", name = "iron-bolts-screws",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/iron-bolts-screws.png",
	category = "hand-craft",
	enabled = false,
	energy_required = 4.5,
	ingredients = {{"iron-plate",1}},
	results = {{"iron-bolts-screws", 3}},
	subgroup = "cartmen-parts",
	order = "c[iron]-c[iron-bolts-screws]",
  },
  { type = "recipe", name = "iron-parts",
    icon = "__CartmenCompleteOverhaul__/graphics/icons/part/iron-parts.png",
	category = "part-pack",
	enabled = false,
	energy_required = 8,
	ingredients = {{"iron-gear-wheel", 2},{"iron-stick", 1},{"iron-bolts-screws", 2}},
	results = {{"iron-parts", 1}},
	subgroup = "cartmen-packs",
	order = "a[part-pack]-c[iron]",
  },
  
})