data:extend({

  { type = "item", name = "crude-circuit",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/crude-circuit.png",
	flags = { "goes-to-main-inventory" },
	order = "e[electronics]-a[simple-electronic]",
	stack_size = 50,
  },
  
  { type = "item", name = "solder",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/solder.png",
	flags = { "goes-to-main-inventory" },
	order = "e[electronics]-a[simple-electronic]",
	stack_size = 200,
  },
  
  { type = "item", name = "crude-circuit-board",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/crude-circuit-board.png",
	flags = { "goes-to-main-inventory" },
	order = "e[electronics]-a[simple-electronic]",
	stack_size = 25,
  },
  
  { type = "item", name = "crude-transistor",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/crude-transistor.png",
	flags = { "goes-to-main-inventory" },
	order = "e[electronics]-a[simple-electronic]",
	stack_size = 100,
  },
  
  { type = "item", name = "standard-circuit-board",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/standard-circuit-board.png",
	flags = { "goes-to-main-inventory" },
	order = "e[electronics]-b[basic-electronic]",
	stack_size = 50,
  },
  
  { type = "item", name = "transistor",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/transistor.png",
	flags = { "goes-to-main-inventory" },
	order = "e[electronics]-b[basic-electronic]",
	stack_size = 200,
  },
  
  { type = "item", name = "resistor",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/resistor.png",
	flags = { "goes-to-main-inventory" },
	order = "e[electronics]-b[basic-electronic]",
	stack_size = 200,
  },
  
  { type = "item", name = "integrated-circuit",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/chip.png",
	flags = { "goes-to-main-inventory" },
	order = "e[electronics]-c[advanced-electronic]-a",
	stack_size = 200,
  },
  
  { type = "item", name = "processing-core",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/processing-core.png",
	flags = { "goes-to-main-inventory" },
	order = "e[electronics]-c[advanced-electronic]-b",
	stack_size = 50,
  },
  
  { type = "item", name = "computing-unit",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/computing-unit.png",
	flags = { "goes-to-main-inventory" },
	order = "e[electronics]-c[advanced-electronic]-c",
	stack_size = 100,
  },
  
  { type = "item", name = "silicon-boule",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/silicon-boule.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 25,
  },
  { type = "item", name = "silicon-wafer",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/silicon-wafer.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  {type = "item", name = "silicon-plate",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/silicon-plate.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
   
})