data:extend({
  { type = "item", name = "small-blast-furnace",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/b_furnace_small_icon.png",
	flags = { "goes-to-quickbar" },	
	stack_size = 50,
	place_result = "small-blast-furnace",
  },  
  { type = "item", name = "small-blast-furnace-2",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/e_b_furnace_small_icon.png",
	flags = { "goes-to-quickbar" },	
	stack_size = 50,
	place_result = "small-blast-furnace-2",
  },
  { type = "item", name = "large-blast-furnace",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/blast-f-icon.png",
	flags = { "goes-to-quickbar" },	
	stack_size = 10,
	place_result = "large-blast-furnace",
  },  
  
  { type = "item", name = "casting-facility",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/cooler.png",
	flags = { "goes-to-quickbar" },	
	stack_size = 50,
	place_result = "casting-facility",
  },
  { type = "item", name = "casting-facility-2",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/cooler-2.png",
	flags = { "goes-to-quickbar" },	
	stack_size = 50,
	place_result = "casting-facility-2",
  },
  
  --[[{ type = "item", name = "mill",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/crusher-icon.png",
	flags = { "goes-to-quickbar" },	
	stack_size = 50,
	place_result = "mill",
  },]]
  { type = "item", name = "mill-2",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/crusher-icon.png",
	flags = { "goes-to-quickbar" },
	stack_size = 50,
	place_result = "mill-2",
  },
  
  { type = "item", name = "flotation-cell",
	icon = "__base__/graphics/icons/storage-tank.png",
	flags = { "goes-to-quickbar" },	
	stack_size = 25,
	place_result = "flotation-cell",
  },
  
  --[[{ type = "item", name = "burner-mining-drill-2",
	icon = "__base__/graphics/icons/burner-mining-drill.png",
	flags = { "goes-to-quickbar" },	
	order = "m-a[burner]",
	stack_size = 25,
	place_result = "burner-mining-drill-2",
  },
  
  { type = "item", name = "burner-mining-drill-3",
	icon = "__base__/graphics/icons/burner-mining-drill.png",
	flags = { "goes-to-quickbar" },	
	order = "m-a[burner]",
	stack_size = 25,
	place_result = "burner-mining-drill-3",
  },
  
  { type = "item", name = "burner-mining-drill-4",
	icon = "__base__/graphics/icons/burner-mining-drill.png",
	flags = { "goes-to-quickbar" },	
	order = "m-a[burner]",
	stack_size = 25,
	place_result = "burner-mining-drill-4",
  },]]
})