data:extend({
  { type = "item", name = "faster-transport-belt",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/faster-transport-belt.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 50,
	place_result = "faster-transport-belt",
  },
  { type = "item", name = "faster-splitter",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/faster-splitter.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 50,
	place_result = "faster-splitter",
  },
  { type = "item", name = "faster-transport-belt-to-ground",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/logistics/faster-transport-belt-to-ground.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 50,
	place_result = "faster-transport-belt-to-ground",
  },
})