data:extend({
  { type = "item", name = "burner-mining-drill",
	icon = "__base__/graphics/icons/burner-mining-drill.png",
	flags = { "goes-to-quickbar" },
	stack_size = 50,
	place_result = "burner-mining-drill",
  },
  { type = "item", name = "burner-mining-drill-2",
	icon = "__base__/graphics/icons/burner-mining-drill.png",
	flags = { "goes-to-quickbar" },
	stack_size = 50,
	place_result = "burner-mining-drill-2",
  },
  { type = "item", name = "burner-mining-drill-3",
	icon = "__base__/graphics/icons/burner-mining-drill.png",
	flags = { "goes-to-quickbar" },
	stack_size = 50,
	place_result = "burner-mining-drill-3",
  },
  
  { type = "item", name = "basic-mining-drill",
	icon = "__base__/graphics/icons/basic-mining-drill.png",
	flags = { "goes-to-quickbar" },
	stack_size = 50,
	place_result = "basic-mining-drill",
  },
  { type = "item", name = "basic-mining-drill-2",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/basic-mining-drill-2.png",
	flags = { "goes-to-quickbar" },
	stack_size = 50,
	place_result = "basic-mining-drill-2",
  },
  { type = "item", name = "basic-mining-drill-3",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/basic-mining-drill-3.png",
	flags = { "goes-to-quickbar" },
	stack_size = 50,
	place_result = "basic-mining-drill-3",
  },
})