data:extend({
  { type = "item", name = "copper-parts",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/copper-parts.png",
	flags = { "goes-to-main-inventory" },
	order = "a-a-a",
	stack_size = 50,
  },
  { type = "item", name = "copper-gear-wheel",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/copper-gear-wheel.png",
	flags = { "goes-to-main-inventory" },
	order = "a-a-b",
	stack_size = 100,
  },
  { type = "item", name = "copper-bolts-screws",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/copper-bolts-screws.png",
	flags = { "goes-to-main-inventory" },
	order = "a-a-c",
	stack_size = 200,
  },
  { type = "item", name = "copper-shaft",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/copper-shaft.png",
	flags = { "goes-to-main-inventory" },
	order = "a-a-d",
	stack_size = 50,
  },
  
  { type = "item", name = "bronze-parts",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/bronze-parts.png",
	flags = { "goes-to-main-inventory" },
	order = "a-b-a",
	stack_size = 50,
  },
  { type = "item", name = "bronze-gear-wheel",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/bronze-gear-wheel.png",
	flags = { "goes-to-main-inventory" },
	order = "a-b-b",
	stack_size = 100,
  },
  { type = "item", name = "bronze-bolts-screws",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/bronze-bolts-screws.png",
	flags = { "goes-to-main-inventory" },
	order = "a-b-c",
	stack_size = 200,
  },
  { type = "item", name = "bronze-shaft",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/bronze-shaft.png",
	flags = { "goes-to-main-inventory" },
	order = "a-b-d",
	stack_size = 50,
  },
  
  { type = "item", name = "iron-parts",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/iron-parts.png",
	flags = { "goes-to-main-inventory" },
	order = "a-c-a",
	stack_size = 50,
  },
  { type = "item", name = "iron-gear-wheel",
	icon = "__base__/graphics/icons/iron-gear-wheel.png",
	flags = { "goes-to-main-inventory" },
	order = "a-c-b",
	stack_size = 100,
  },
  { type = "item", name = "iron-bolts-screws",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/iron-bolts-screws.png",
	flags = { "goes-to-main-inventory" },
	order = "a-c-c",
	stack_size = 200,
  },
  { type = "item", name = "iron-stick",
	icon = "__base__/graphics/icons/iron-stick.png",
	flags = { "goes-to-main-inventory" },
	order = "a-c-d",
	stack_size = 50,
  },
  
  { type = "item", name = "steel-parts",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/steel-parts.png",
	flags = { "goes-to-main-inventory" },
	order = "a-d-a",
	stack_size = 50,
  },
  { type = "item", name = "steel-gear-wheel",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/steel-gear-wheel.png",
	flags = { "goes-to-main-inventory" },
	order = "a-d-b",
	stack_size = 100,
  },
  { type = "item", name = "steel-bolts-screws",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/steel-bolts-screws.png",
	flags = { "goes-to-main-inventory" },
	order = "a-d-c",
	stack_size = 200,
  },
  { type = "item", name = "steel-shaft",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/steel-shaft.png",
	flags = { "goes-to-main-inventory" },
	order = "a-d-d",
	stack_size = 50,
  },
  
  { type = "item", name = "titanium-parts",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/titanium-parts.png",
	flags = { "goes-to-main-inventory" },
	order = "a-e-a",
	stack_size = 50,
  },
  { type = "item", name = "titanium-gear-wheel",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/titanium-gear-wheel.png",
	flags = { "goes-to-main-inventory" },
	order = "a-e-b",
	stack_size = 100,
  },
  { type = "item", name = "titanium-bolts-screws",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/titanium-bolts-screws.png",
	flags = { "goes-to-main-inventory" },
	order = "a-e-c",
	stack_size = 200,
  },
  { type = "item", name = "titanium-shaft",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/titanium-shaft.png",
	flags = { "goes-to-main-inventory" },
	order = "a-e-d",
	stack_size = 50,
  },
  
  { type = "item", name = "rubber",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/rubber.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  { type = "item", name = "rubber-belt",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/rubber-belt.png",
	flags = { "goes-to-main-inventory" },
	order = "a-c-e",
	stack_size = 50,
  },
  { type = "item", name = "rubber-seal",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/part/rubber-seal.png",
	flags = { "goes-to-main-inventory" },
	order = "a-c-e",
	stack_size = 50,
  },
  
})