data:extend({
  { type = "item", name = "bronze-plate",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/plate/bronze-plate.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  { type = "item", name = "bronze-ore",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/ore/bronze-ore.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "tin-plate",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/plate/tin-plate.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "lead-plate",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/plate/lead-plate.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "titanium-plate",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/plate/titanium-plate.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "tungsten-carbide",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/plate/tungsten-carbide.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
  
  { type = "item", name = "aluminium-plate",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/plate/aluminium-plate.png",
	flags = { "goes-to-main-inventory" },
	stack_size = 200,
  },
})