data:extend({
  { type = "item", name = "gun-turret-2",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/gun-turret-2.png",
	flags = { "goes-to-quickbar" },
	subgroup = "defensive-structure",
	order = "b[turret]-b[gun-turret-2]-b",
	stack_size = 50,
	place_result = "gun-turret-2",
  },
  { type = "item", name = "gun-turret-3",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/gun-turret-3.png",
	flags = { "goes-to-quickbar" },
	subgroup = "defensive-structure",
	order = "b[turret]-b[gun-turret-3]-c",
	stack_size = 50,
	place_result = "gun-turret-3",
  },
  { type = "item", name = "gun-turret-4",
	icon = "__CartmenCompleteOverhaul__/graphics/icons/entity/gun-turret-4.png",
	flags = { "goes-to-quickbar" },
	subgroup = "defensive-structure",
	order = "b[turret]-b[gun-turret-4]-d",
	stack_size = 50,
	place_result = "gun-turret-4",
  },
})