data:extend({
  { type = "fluid", name = "liquid-iron",
    default_temperature = 1200,
	max_temperature = 1200,
	heat_capacity = "0KJ",
	base_color = {r= 96, g= 96, b= 96},
	flow_color = {r= 96, g= 96, b= 96},
	icon = "__CartmenCompleteOverhaul__/graphics/icons/fluid/liquid-iron.png",
	pressure_to_speed_ratio = 0.4,
	flow_to_energy_ratio = 0.59,
  },
  
  { type = "fluid", name = "liquid-steel",
    default_temperature = 1200,
	max_temperature = 1200,
	heat_capacity = "0KJ",
	base_color = {r= 51, g= 0, b= 102},
	flow_color = {r= 51, g= 0, b= 102},
	icon = "__CartmenCompleteOverhaul__/graphics/icons/fluid/liquid-steel.png",
	pressure_to_speed_ratio = 0.4,
	flow_to_energy_ratio = 0.59,
  },
  
  { type = "fluid", name = "liquid-copper",
    default_temperature = 1200,
	max_temperature = 1200,
	heat_capacity = "0KJ",
	base_color = {r= 204, g= 102, b= 0},
	flow_color = {r= 204, g= 102, b= 0},
	icon = "__CartmenCompleteOverhaul__/graphics/icons/fluid/liquid-copper.png",
	pressure_to_speed_ratio = 0.4,
	flow_to_energy_ratio = 0.59,
  },
  
  { type = "fluid", name = "liquid-bronze",
    default_temperature = 1200,
	max_temperature = 1200,
	heat_capacity = "0KJ",
	base_color = {r= 147, g= 107, b= 73},
	flow_color = {r= 204, g= 102, b= 0},
	icon = "__CartmenCompleteOverhaul__/graphics/icons/fluid/liquid-bronze.png",
	pressure_to_speed_ratio = 0.4,
	flow_to_energy_ratio = 0.59,
  },
  
  { type = "fluid", name = "liquid-titanium",
    default_temperature = 1200,
	max_temperature = 1200,
	heat_capacity = "0KJ",
	base_color = {r= 110, g= 137, b= 126},
	flow_color = {r= 158, g= 179, b= 169},
	icon = "__CartmenCompleteOverhaul__/graphics/icons/fluid/liquid-titanium.png",
	pressure_to_speed_ratio = 0.4,
	flow_to_energy_ratio = 0.59,
  },
  
  { type = "fluid", name = "liquid-silicon",
    default_temperature = 1200,
	max_temperature = 1200,
	heat_capacity = "0KJ",
	base_color = {r=83, g=83, b=84},
    flow_color = {r=83, g=83, b=84},
	icon = "__CartmenCompleteOverhaul__/graphics/icons/fluid/liquid-silicon.png",
	pressure_to_speed_ratio = 0.4,
	flow_to_energy_ratio = 0.59,
  },
})